- hosts: all
  tasks:
    - name: Installing nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: Disable Root Login
      lineinfile:
           dest=/var/www/html/index.html
           regexp='^Welcome to nginx!'
           line="<h1><p><script>document.write(new Date().toLocaleDateString());</script></p></h1>"
           state=present