pipeline {
    agent any

    stage {
        stage ('git clone') {
            steps {
                echo 'git clone'
            }
        }
        stage ('build') {
            steps{
                echo 'build'
            }
        }
        stage ('deploy') {
            steps{
                echo 'deploy'
            }
        }
    }
}