pipeline {
    agent any
    tools {
        maven "m3"
    }
    stages {
        stage('git clone'){
            steps {
                git 'https://github.com/dkgnim/test50.git'
            }
        }      
    }
    stages {
        stage('build'){
            steps{
                sh 'mvn package'
            }
        }
    }
    stage {
        stage('deploy'){
            steps{
                
            }
        }
    }
}