 pipeline {
     agent {
         docker {
             image 'maven:3.6-jdk-8'
         }
     }
    stages {
        stage('Clone project') {
            git 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        }
    }
    stages {
        stage('Build project'){
            
        }
    }
 }