 pipeline {
     agent {
         docker {
             image 'maven:3.6-jdk-8'
         }
     }
    stages {
        stage('Clone project') {
            git 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        }
    }
    stages {
        stage('Build project'){
            sh 'mvn package -f /boxfuse/pom.xml'
        }
    }
    stages {
        stage('Build docker image and tag'){

        }
    }
 }