---
- name: Installing maven
  apt: name={{item}} state=present
  with_items:
    - maven
    - git

- name: Clone repo
  git: repo='https://github.com/boxfuse/boxfuse-sample-java-war-hello.git' dest={{path_boxfuse}} clone=yes

- name: Building war file
  shell: mvn -f {{path_boxfuse}}/pom.xml package

- name: copy war to server
  fetch: src={{path_boxfuse}}/target/hello-1.0.war dest=/tmp/ flat=yes